In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
(np.ones(20) * 2) ** np.arange(1, 21) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
np.sum(0.1 ** (3 * np.arange(6)) * 0.2 ** (4 * np.arange(6)))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
# без numpy:
4 * [4 * [1, 0], 4 * [0, 1]]

[[1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1]]

In [5]:
# с numpy:
np.block(4 * [4 * [np.eye(2)]])

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))

def to_polar(row):
    x, y = row
    return np.sqrt(x ** 2 + y ** 2), np.arctan(y / x)

np.apply_along_axis(to_polar, 1, X)

array([[0.68124802, 0.17275379],
       [0.43768679, 0.03940753],
       [0.54535231, 0.33722351],
       [1.34619085, 0.76670628],
       [1.22223591, 0.67980814]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
X = np.random.random((10, 10))

arg = np.argmax(X)
(arg // 10, arg % 10)

(0, 0)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [8]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

def dist(x):
    return np.sqrt((x[0] - y[0][0]) ** 2 + (x[1] - y[0][1]) ** 2)

np.argmin(np.apply_along_axis(dist, 1, X))

9

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [9]:
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    elif x >= 2:
        return x**2 + 4*x - 4
    else:
        return x +6

f_vec = np.vectorize(f)
f_vec(np.linspace(-3, 3, 21))

array([ 9.  ,  7.89,  6.96,  6.21,  5.64,  5.25,  5.04,  5.01,  5.16,
        5.49,  6.  ,  6.3 ,  6.6 ,  6.9 ,  7.2 ,  7.5 ,  7.8 ,  8.81,
       11.36, 14.09, 17.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [10]:
X = np.random.random((10, 10))

X_new = X - X.mean(axis=1, keepdims=True)
X_new.mean(axis=1)

array([-2.22044605e-17, -5.55111512e-17, -3.33066907e-17, -2.22044605e-17,
       -3.33066907e-17,  4.44089210e-17,  1.11022302e-17,  1.11022302e-16,
        1.22124533e-16,  1.11022302e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [11]:
X = np.random.normal(loc=5, scale=2., size=1000)

X.mean(), X.var()

(5.010748255672528, 4.085974262420746)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [12]:
def f(row, shift):
    return np.roll(row, shift=shift)

vec_f = np.vectorize(f, signature='(m),()->(m)')

X = np.array([np.arange(5)] * 5)
vec_f(X, -np.arange(5))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [13]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 3, 0, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [16]:
def sample(x, c):
    assert len(x) > 0
    s = np.sum(x)
    val = s * np.random.random(c)
    val = np.reshape(val, (-1, 1))
    x = np.array(x)
    x_sum = np.cumsum(x)
    m = (x_sum <= val)
    res = np.sum(m, axis=1)

    return res


sample([50, 3, 1, 7, 20], 5)

array([4, 0, 0, 0, 0])